services:
  app:
    build: .
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - DATA_PATH=/app/var/data
      - IMAGES_PATH=/app/var/data/images
    volumes:
      - ./var/data:/app/var/data
    restart: unless-stopped
    networks:
      - webproxy

networks:
  webproxy:
    external: true
    name: ${PROXY_NETWORK:-webproxy}
